#!/usr/bin/env bash
# Installs nginx web server
# Nginx should be listening on port 80

apt-get -y update
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.html
service nginx restart
