#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page
# 404 error returns "Ceci n'est pas une page"
# Response contains a custom header => X-Served-By: <host_name>

# shellcheck disable=SC2154

apt-get update -y
apt-get install nginx -y

echo "Hello World!" > /var/www/html/index.html
service nginx start

# Backup existing nginx configuration file
NGINX_CONFIG_FILE="/etc/nginx/sites-available/default"
cp "$NGINX_CONFIG_FILE" "$NGINX_CONFIG_FILE".bak

# Configure /redirect_me path
REDIRECTION_CONFIG_STRING="server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/github.com\/awinabaab?tab=repositories;\n\t}"
sed -i "s/server_name _;/$REDIRECTION_CONFIG_STRING/" "$NGINX_CONFIG_FILE"

# Configure custom 404 page
echo -e "Ceci n'est pas une page\n" > /var/www/html/custom_404.html
ERROR_CONFIG_STRING="server_name _; \n\n\terror_page 404 \/custom_404.html;\n\n\tlocation \/custom_404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sed -i "s/server_name _;/$ERROR_CONFIG_STRING/" "$NGINX_CONFIG_FILE"

# Configure custom header
REPLACE_STRING="error_log \/var\/log\/nginx\/error.log;"
HEADER_DIRECTIVE="$REPLACE_STRING\n\n\t##\n\t# Custom Headers\n\t##\n\t\n\tadd_header X-Served-By \"$HOSTNAME\";"

sed -i "s/$REPLACE_STRING/$HEADER_DIRECTIVE/" /etc/nginx/nginx.conf

# Check if the config file is valid: reload nginx if true
nginx -t
exit_code=$?

if (( exit_code == 0 ))
then
	service nginx restart
fi
