#!/usr/bin/env bash
# Configures nginx to run and listen on port 80 of all the server's active IPv4 IPs
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
pkill -1 -f "/usr/sbin/nginx"
