#!/usr/bin/env bash
#Manages my_process_script


if [ "$1" = "start" ]
then
	sudo ./manage_my_process &
	p_id="$!"
	echo "$p_id" > /var/run/my_process.pid
	echo "manage_my_process started"
elif [ "$1" = "stop" ]
then
	kill "$(cat /var/run/my_process.pid)"
	sudo rm /var/run/my_process.pid
	echo "manage_my_process stopped"
elif [ "$1" = "restart" ]
then
	#Stop process
	kill "$(cat /var/run/my_process.pid)"
	sudo rm /var/run/my_process.pid
	#Start process
	sudo ./manage_my_process &
	echo "$p_id" > /var/run/my_process.pid
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
