#!/usr/bin/env bash
#Displays:
#	"To infinity and beyond" indefinitely
#	With a "sleep 2" in between each iteration
#	"I am invincible!!!" when receiving a "SIGTERM" signal
while ((1))
do
	trap 'echo "I am invincible!!!";' TERM
	echo "To infinity and beyond"
	sleep 2
done
