#!/usr/bin/env bash
#Displays Best School 10 times but for the 9th iteration, displays Best School and the Hi  on a new line
i=1
while [ "$i" -lt 11 ]
do
	echo "Best School"
	if [ "$i" -eq 9 ]
	then
		echo "Hi"
	fi
	i=$(("$i"+1))
done
