#!/usr/bin/env bash
hours=0
while [ "$hours" -lt 24 ]
do
	minutes=1
	echo "Hour: $hours"
	while [ "$minutes" -lt 60 ]
	do
		echo "$minutes"
		minutes=$(("$minutes"+1))
	done
	hours=$(("$hours"+1))
done
