#!/usr/bin/env bash
#Displays the time for 12 hours and 59 minutes:
#	displays hours from 0 to 12
#	displays minutes from 1 to 59
hours=0
while [ "$hours" -lt 13 ]
do
	minutes=1
	echo "Hour: $hours"
	while [ "$minutes" -lt 60 ]
	do
		echo "$minutes"
		minutes=$(("$minutes"+1))
	done
	hours=$(("$hours"+1))
done
