#!/usr/bin/env bash
#Displays the content of the current directory in list format
#	where only the part of the name after the first das is displayed
for file in *
do
	echo "$file" | cut -d "-" -f2-
done
