#!/usr/bin/env bash
#Gives information about the "school" file
filename="school"
if [ -e "$filename" ]
then
	echo "$filename file exists"
else
	echo "$filename file does not exist"
	exit
fi

if [ -s "$filename" ]
then
	echo "$filename file is not empty"
else
	echo "$filename file is empty"
fi

if [ -f "$filename" ]
then
	echo "$filename is a regular file"
fi
