#!/usr/bin/env bash
# Runs nginx web server (listening on port 80) as nginx user
pkill -f apache2
chmod 644 /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-available/default
sudo -u nginx -s service nginx start
